# Generated by Django 3.1.14 on 2022-08-05 14:58

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import here_for_change.municipalities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('municipality_code', models.CharField(max_length=6, unique=True)),
                ('municipality_type', models.CharField(choices=[('Metropolitan', 'Metro'), ('District', 'District'), ('Local', 'Local')], max_length=25)),
                ('province', models.CharField(choices=[('EasternCape', 'Eastern Cape'), ('Freestate', 'Free State'), ('Gauteng', 'Gauteng'), ('KwaZuluNatal', 'KwaZulu-Natal'), ('Limpopo', 'Limpopo'), ('Mpumalanga', 'Mpumalanga'), ('NorthernCape', 'Northern Cape'), ('NorthWest', 'North West'), ('WesternCape', 'Western Cape')], max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=here_for_change.municipalities.models.ward_slug)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipalities.municipality')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
