# Generated by Django 3.2.15 on 2022-08-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='map_default_zoom',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='municipality',
            name='map_latitude',
            field=models.DecimalField(decimal_places=7, default=-33.9249, max_digits=10),
        ),
        migrations.AddField(
            model_name='municipality',
            name='map_longitude',
            field=models.DecimalField(decimal_places=7, default=18.4241, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='map_default_zoom',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='ward',
            name='map_latitude',
            field=models.DecimalField(decimal_places=7, default=-33.9249, max_digits=10),
        ),
        migrations.AddField(
            model_name='ward',
            name='map_longitude',
            field=models.DecimalField(decimal_places=7, default=18.4241, max_digits=10),
        ),
    ]
