# Generated by Django 3.2.15 on 2022-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0002_auto_20220810_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
