# Generated by Django 3.2.15 on 2022-09-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0003_municipality_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='municipality_type',
            field=models.CharField(choices=[('Metropolitan', 'Metro'), ('Local', 'Local')], max_length=25),
        ),
    ]
