# Generated by Django 3.2.15 on 2022-09-16 12:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0004_alter_municipality_municipality_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Ward Boundary data'),
        ),
    ]
