# Generated by Django 3.2.15 on 2022-09-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0006_municipality_area_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='map_longitude',
        ),
    ]
