# Generated by Django 3.2.15 on 2022-09-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0006_municipality_area_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='map_longitude',
        ),
        migrations.CreateModel(
            name='WardDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=90)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('json', 'Json')], default='string', max_length=40)),
                ('field_value', models.CharField(max_length=90)),
                ('stage', models.CharField(choices=[('staging', 'Staging version'), ('production', 'Production version')], default='staging', max_length=40)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipalities.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
