# Generated by Django 3.2.15 on 2022-09-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0007_auto_20220926_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='warddetail',
            name='feedback',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='warddetail',
            name='field_type',
            field=models.CharField(choices=[('string', 'String'), ('int', 'Integer'), ('float', 'Float'), ('json', 'Json'), ('date', 'Date'), ('email', 'Email'), ('phone', 'Phone')], default='string', max_length=40),
        ),
    ]
