# Generated by Django 3.2.15 on 2022-09-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0008_auto_20220926_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetail',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
