# Generated by Django 3.2.15 on 2022-11-09 13:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0009_alter_warddetail_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='map_longitude',
        ),
    ]
