# Generated by Django 3.2.15 on 2022-11-09 15:25

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0010_auto_20221109_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Municipality Boundary data'),
        ),
    ]
