# Generated by Django 3.2.15 on 2022-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0011_auto_20221109_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetail',
            name='feedback',
            field=models.JSONField(default={'negative': 0, 'positive': 0}),
        ),
    ]
