# Generated by Django 3.2.15 on 2022-12-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0012_municipalitydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalitydetail',
            name='field_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='municipalitydetail',
            name='field_value',
            field=models.CharField(max_length=200),
        ),
    ]
