# Generated by Django 3.2.15 on 2022-12-08 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0012_alter_warddetail_feedback'),
        ('municipalities', '0013_auto_20221205_1507'),
    ]

    operations = [
    ]
