# Generated by Django 3.2.15 on 2022-12-08 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0014_merge_20221208_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindMyWardCouncillorFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('feedback', models.CharField(max_length=250)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipalities.ward')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
