# Generated by Django 3.2.16 on 2023-01-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0014_merge_20221208_1519'),
        ('municipalities', '0015_findmywardcouncillorfeedback'),
    ]

    operations = [
    ]
