# Generated by Django 3.2.16 on 2023-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0016_merge_20230111_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
