# Generated by Django 3.2.16 on 2023-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0017_alter_warddetail_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetail',
            name='feedback',
            field=models.JSONField(default={'negative': 0, 'positive': 0}),
        ),
    ]
