# Generated by Django 3.2.16 on 2023-01-13 05:06

from django.db import migrations, models
import here_for_change.municipalities.models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0018_alter_warddetail_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetail',
            name='feedback',
            field=models.JSONField(default=here_for_change.municipalities.models.default_feedback),
        ),
    ]
