# Generated by Django 3.2.16 on 2023-01-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0017_alter_ward_name'),
        ('municipalities', '0019_alter_warddetail_feedback'),
    ]

    operations = [
    ]
