# Generated by Django 3.2.16 on 2023-01-24 00:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0020_merge_20230113_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('province_code', models.CharField(max_length=6, unique=True)),
                ('area_number', models.IntegerField(null=True)),
                ('map_default_zoom', models.IntegerField(default=12)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Province Boundary data')),
            ],
            options={
                'verbose_name_plural': 'Provinces',
            },
        ),
        migrations.AlterField(
            model_name='municipality',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='municipalities.province'),
        ),
    ]
