# Generated by Django 3.2.16 on 2023-01-29 22:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0024_alter_province_boundary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326, verbose_name='Province Boundary data'),
        ),
    ]
