# Generated by Django 3.2.16 on 2023-01-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0025_alter_province_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='area_number',
            field=models.IntegerField(null=True),
        ),
    ]
