# Generated by Django 3.2.16 on 2023-01-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municipalities', '0026_ward_area_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipality',
            name='area_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='area_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='area_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
