name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose
        run: docker-compose up -d
      - name: Load demo data
        run: docker compose run --rm web python manage.py loaddata demo-data
        with:
          wait-on: 'http://localhost:8000'
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          wait-on: 'http://localhost:8000'