name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose
        run: docker-compose up -d
      - name: Migrate
        run: docker compose run --rm web python manage.py migrate
      - name: Load demo data
        run: docker compose run --rm web python manage.py loaddata demo-data
      - name: Wait on
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http://localhost:8000
      - name: Cypress run
        uses: cypress-io/github-action@v4
        