name: Django Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker compose up
        run: docker-compose up -d
      - name: Docker compose test
        run: docker-compose run --rm web python manage.py test